import logging

import openai

from inference.schemas.constants import OPEN_API_KEY

# Create a logger
logger = logging.getLogger(__name__)

# Set your OpenAI API key
openai.api_key = OPEN_API_KEY


class GPT3:
    def __init__(self):
        self.api_key = OPEN_API_KEY  # Add any initialization logic here

    def generate(self, prompt: str, max_tokens: int = 150) -> str:
        """
        Generates a completion from the GPT-3 model
        :param prompt: The text used to prompt the model
        :param max_tokens: Maximum number of tokens in the completion
        :return: The completion generated by the GPT-3 model
        """
        try:
            response = openai.Completion.create(
                engine="davinci",  # Specify the GPT-3 engine to use
                prompt=prompt,
                max_tokens=max_tokens,
            )
            return response.choices[0].text
        except Exception as e:
            logger.error(f"An error occurred during GPT-3 completion: {e}")
            return None
